services:
  # Application Service
  app:
    container_name: blog_php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/app
    ports:
      - "9000:9000"
    working_dir: /var/www/app
    depends_on:      
    - db


  # Database Service
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
    - ./mysql_data:/var/lib/mysql


  #PhpMyAdmin Service
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
    - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
    - "8080:80"



  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/app
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
